### ISSUE TITLE
Question related to pgadmin

### ISSUE THREAD

**Issue by rbadr** [asaikali/docker-compose-postgres#1]
Hello @asaikali 👋 

Very nice sample, good job 👍 

I just have a question, as I tried it, I have an error with pgadmin `UnboundLocalError: local variable 'user_id' referenced before assignment`, because I'm setting PGADMIN_CONFIG_SERVER_MODE to False.

Did you encounter at any time this issue ? 
Thank you !

**Comment by asaikali** [comment]
no I did not. If you clone this repo and launch it are you getting an error?

**Comment by rbadr** [comment]
It's all good now @asaikali , thanks !
